services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - prometheus
      - grafana
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker
    command: poetry run celery -A app.celery_tasks.notifications worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis

  db:
    image: postgres:16
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana

volumes:
  postgres_data:


