"""edit user model: delete password in model

Revision ID: 24e10db6dd3b
Revises: 1f73f8d8f041
Create Date: 2025-04-29 01:31:08.553095

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24e10db6dd3b"
down_revision: Union[str, None] = "1f73f8d8f041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
