"""create users table delete password hash

Revision ID: 5587be0ef7b5
Revises: bf02a912bf54
Create Date: 2025-04-26 18:41:02.523306

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5587be0ef7b5"
down_revision: Union[str, None] = "bf02a912bf54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_hash", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
