"""update model

Revision ID: 6f4ba17150bc
Revises: 455b206dd9d6
Create Date: 2025-04-28 14:36:07.806653

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f4ba17150bc"
down_revision: Union[str, None] = "455b206dd9d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tasks_user_id_fkey", "tasks", type_="foreignkey")
    op.drop_column("tasks", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key("tasks_user_id_fkey", "tasks", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###
