"""add password for user

Revision ID: 9f48ab7e8426
Revises: 5587be0ef7b5
Create Date: 2025-04-27 15:20:24.355712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f48ab7e8426"
down_revision: Union[str, None] = "5587be0ef7b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["password"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "password")
    # ### end Alembic commands ###
