"""update user model with fastapi users

Revision ID: b525ab74a868
Revises: 24e10db6dd3b
Create Date: 2025-04-29 15:43:56.078747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b525ab74a868"
down_revision: Union[str, None] = "24e10db6dd3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_username", table_name="users")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    # ### end Alembic commands ###
