"""update user model

Revision ID: b60aadba521a
Revises: 89325fdb61ec
Create Date: 2025-04-29 20:28:36.437843

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b60aadba521a"
down_revision: Union[str, None] = "89325fdb61ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index("ix_users_username", table_name="users")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
